[charts/karavi-observability] Observability release v1.1.0
dell/helm-charts pull request #108
Opened 2022-03-11 18:29 UTC by LJ-Software

#### Is this a new chart?

No

#### What this PR does / why we need it:

Updating the Observability chart to point to the newly released v1.1.0 images.

#### Which issue(s) is this PR associated with:

N/A

#### Special notes for your reviewer:

#### Checklist:

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Chart Version bumped
- [x] Variables are documented in the chart README.md
- [x] Title of the PR starts with the chart name (e.g. `[charts_dir/mychartname]`) if applicable

2022-03-11 18:48 UTC, AronAtDell submitted a review, later dismissed

2022-03-18 16:52 UTC, hoppea2 approved these changes

2022-03-18 17:02 UTC, gallacher approved these changes
LGTM

2022-03-18 17:03 UTC, hoppea2 requested changes
Pending RFD date

2022-03-23 13:36 UTC, shaynafinocchiaro approved these changes

2022-03-23 13:36 UTC, hoppea2 approved these changes

2022-03-23 13:36 UTC, merged