add support for PowerScale topology
dell/helm-charts pull request #123
Opened 2022-06-14 03:42 UTC by YianZong

#### Is this a new chart?

No

#### What this PR does / why we need it:
enable PowerScale topology

#### Which issue(s) is this PR associated with 
- #334: https://github.com/dell/helm-charts/

#### Special notes for your reviewer:
This code change has been verified along with changes in [karavi-topology](https://github.com/dell/karavi-topology) [PR#116] (https://github.com/dell/karavi-topology/pull/116)

#### Checklist:

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Chart Version bumped
- [ ] Variables are documented in the chart README.md
- [ ] Title of the PR starts with the chart name (e.g. `[charts_dir/mychartname]`) if applicable

2022-06-14 05:41 UTC, forrestxia submitted a review, later dismissed
LGTM.
@YianZong pls check the end to end logic to ensure this change is respected.

2022-06-23 06:27 UTC, taohe1012 approved these changes

2022-06-24 08:00 UTC, forrestxia requested changes

2022-06-24 08:00 UTC, forrestxia commented on charts/karavi-observability/Chart.yaml
>  name: karavi-observability
shall we use 1.3.0? @YianZong

2022-06-24 08:02 UTC, forrestxia commented on charts/karavi-observability/Chart.yaml
>  name: karavi-observability
Rethinking, seems 1.2.1 is ok for now.

2022-06-24 08:03 UTC, forrestxia approved these changes

2022-06-24 12:47 UTC, shaynafinocchiaro commented
Can these changes point to the karavi-observability-release branch instead of main. We've recently bumped the versions in Chart.yaml as well. Thank you!

2022-06-27 05:09 UTC, YianZong commented
> Can these changes point to the karavi-observability-release branch instead of main. We've recently bumped the versions in Chart.yaml as well. Thank you!

Thanks, @shaynafinocchiaro ! Done.

2022-06-27 08:43 UTC, baoy1 submitted a review, later dismissed

2022-06-27 08:47 UTC, forrestxia approved these changes

2022-06-27 15:15 UTC, shaynafinocchiaro approved these changes

2022-06-28 08:02 UTC, forrestxia approved these changes

2022-06-28 08:02 UTC, baoy1 approved these changes

2022-06-28 08:32 UTC, P-Cao approved these changes

2022-06-28 13:57 UTC, sharmilarama commented on charts/karavi-observability/Chart.yaml
> +appVersion: "1.2.1"
this will be 1.3.0, every new release updates the minor version. Only patch releases increment the last digit.

2022-06-28 13:57 UTC, sharmilarama commented on charts/karavi-observability/Chart.yaml
> +version: 1.2.1
same comment as above

2022-06-28 14:53 UTC, YianZong commented on charts/karavi-observability/Chart.yaml
> +version: 1.2.1
@sharmilarama Thanks! Addressed both.

2022-06-28 17:34 UTC, sharmilarama submitted a review, later dismissed

2022-06-28 23:48 UTC, forrestxia approved these changes

2022-06-29 01:54 UTC, taohe1012 submitted a review, later dismissed

2022-06-29 02:22 UTC, baoy1 submitted a review, later dismissed

2022-06-29 02:30 UTC, P-Cao approved these changes

2022-06-29 05:28 UTC, baoy1 approved these changes

2022-06-29 05:47 UTC, forrestxia approved these changes

2022-06-29 05:48 UTC, P-Cao approved these changes

2022-06-29 05:51 UTC, YianZong commented
I signed the commit and had to push it again. @sharmilarama @shaynafinocchiaro please help review to approve it again, thank you!

2022-06-29 06:58 UTC, taohe1012 approved these changes

2022-06-29 12:00 UTC, sharmilarama approved these changes

2022-06-29 12:38 UTC, merged