Ingress removal storage service
dell/helm-charts pull request #198
Opened 2023-04-03 18:19 UTC by IsaiasA1

#### Is this a new chart?

Yes

#### What this PR does / why we need it:
This PR removes the storage-service ingress because karavictl will now be sending requests to the proxy-server.

Which issue(s) is this PR associated with:

#### Which issue(s) is this PR associated with:

- #dell/csm#725

#### Special notes for your reviewer:

#### Checklist:

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Chart Version bumped
- [x] Variables are documented in the chart README.md
- [ ] Title of the PR starts with the chart name (e.g. `[charts_dir/mychartname]`) if applicable

2023-04-03 21:08 UTC, sharmilarama requested changes
This should target release-v1.7.0 branch, not main

2023-04-10 19:16 UTC, shaynafinocchiaro submitted a review, later dismissed

2023-04-11 13:19 UTC, atye submitted a review, later dismissed

2023-04-11 14:01 UTC, alikdell approved these changes

2023-04-11 19:56 UTC, atye approved these changes

2023-04-11 19:56 UTC, sharmilarama approved these changes

2023-04-11 20:11 UTC, merged