Volume limits p max
dell/helm-charts pull request #240
Opened 2023-07-24 12:41 UTC by tssushma

#### Is this a new chart?

Yes/No

#### What this PR does / why we need it:
This feature helps in limiting the number of Volume per node by the user.

#### Which issue(s) is this PR associated with:
https://github.com/dell/csm/issues/878

- #Issue_Number
https://github.com/dell/csm/issues/878

#### Special notes for your reviewer:

#### Checklist:

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Chart Version bumped
- [ ] Variables are documented in the chart README.md
- [ ] Title of the PR starts with the chart name (e.g. `[charts_dir/mychartname]`) if applicable

2023-07-25 08:05 UTC, delldubey requested changes

2023-07-25 08:05 UTC, delldubey commented on charts/csi-powermax/templates/node.yaml
> -{{- if or (eq .Values.migration.enabled true) (eq .Values.openshift true) }}
check this, the old file should not be removed

2023-07-26 08:25 UTC, santhoshhs10 submitted a review, later dismissed

2023-07-27 05:55 UTC, delldubey approved these changes
lgtm

2023-07-27 06:29 UTC, chaganti-rajitha commented
I hope these changes are related to release-1.8 then Please change the main branch to release-v1.8.0 and also update the values.yaml in container-storage-modules chart as well.

2023-07-31 14:46 UTC, tssushma commented
> I hope these changes are related to release-1.8 then Please change the main branch to release-v1.8.0 and also update the values.yaml in container-storage-modules chart as well.

@chaganti-rajitha updated the driver version and also changed the merge to branch release-1.8

2023-08-01 10:52 UTC, shanmydell approved these changes

2023-08-02 06:39 UTC, chaganti-rajitha reviewed
Please make changes in the values.yaml of container-storage-modules for powermax

2023-08-03 06:40 UTC, chaganti-rajitha approved these changes
LGTM

2023-08-03 07:12 UTC, tssushma commented
> Please make changes in the values.yaml of container-storage-modules for powermax

Yes changed the values.yaml of container-storage-modules for powermax

2023-08-04 08:12 UTC, shanmydell approved these changes

2023-08-04 09:20 UTC, merged