Driver and Modules Version Update
dell/helm-charts pull request #348
Opened 2024-01-08 12:33 UTC by rishabhatdell

#### Is this a new chart?

Yes/No

#### What this PR does / why we need it:

#### Which issue(s) is this PR associated with:

- #Issue_Number

#### Special notes for your reviewer:

#### Checklist:

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Chart Version bumped
- [ ] Variables are documented in the chart README.md
- [ ] Title of the PR starts with the chart name (e.g. `[charts_dir/mychartname]`) if applicable

2024-01-09 07:12 UTC, AkshaySainiDell requested changes

2024-01-09 07:12 UTC, AkshaySainiDell commented on charts/container-storage-modules/Chart.yaml
Module version update is missing in this file.

2024-01-09 14:54 UTC, shanmydell requested changes
Are observability,authorization,topology repos going to have releases? @rishabhatdell

2024-01-10 11:33 UTC, shanmydell commented
@rishabhatdell : Those changes will not impact modules much, awaiting confirmation, will update the comment based on confirmation

2024-01-12 05:16 UTC, KshitijaKakde commented on charts/container-storage-modules/Chart.yaml
Updated the module version

2024-01-17 11:00 UTC, rishabhatdell commented
@shanmydell any updates on modules?

2024-01-19 14:28 UTC, shanmydell approved these changes

2024-01-22 04:52 UTC, AkshaySainiDell approved these changes

2024-01-22 10:10 UTC, merged