Remove check on maximum version of kube
dell/helm-charts pull request #410
Opened 2024-04-17 15:23 UTC by coulof

#### Is this a new chart?

Yes

#### What this PR does / why we need it:
This PR allows to install the CSI drivers on a Kubernetes version that is above the internally tested one

#### Which issue(s) is this PR associated with:

- KRV-13492

#### Special notes for your reviewer:
`helm lint` passed and this has been tested with csi-powerflex only

#### Checklist:

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Chart Version bumped
- [ ] Variables are documented in the chart README.md
- [ ] Title of the PR starts with the chart name (e.g. `[charts_dir/mychartname]`) if applicable

2024-04-17 15:27 UTC, shaynafinocchiaro commented on charts/csi-isilon/Chart.yaml
> -kubeVersion: ">= 1.21.0 < 1.31.0"
The minimum kube version isn't consistent across drivers, do you know why that is?

2024-04-17 16:58 UTC, donatwork approved these changes
This is a change that has been long overdue. Sometimes you just have to go out and do it. Thanks Florian.

2024-04-18 06:53 UTC, shanmydell requested changes

2024-04-18 06:53 UTC, shanmydell commented on charts/csi-unity/Chart.yaml
>  # If you are using a complex K8s version like "v1.24.3-mirantis-1", use this kubeVersion check instead
@coulof : Remove this comment as well as it is related to check

2024-04-18 06:54 UTC, shanmydell approved these changes

2024-04-18 06:54 UTC, merged