Powermax resiliency changes
dell/helm-charts pull request #421
Opened 2024-05-09 13:59 UTC by delldubey

#### Is this a new chart?

No

#### What this PR does / why we need it:
- Podmon installation with the driver
#### Which issue(s) is this PR associated with:

- https://github.com/dell/csm/issues/1082

#### Special notes for your reviewer:

#### Checklist:

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Chart Version bumped
- [ ] Variables are documented in the chart README.md
- [ ] Title of the PR starts with the chart name (e.g. `[charts_dir/mychartname]`) if applicable

2024-05-17 10:37 UTC, boyamurthy approved these changes
LGTM.

2024-05-20 08:13 UTC, AkshaySainiDell requested changes

2024-05-20 11:33 UTC, AkshaySainiDell requested changes

2024-05-20 11:33 UTC, AkshaySainiDell commented on charts/csi-powermax/templates/controller.yaml
> +                    {{- toYaml .Values.podmon.controller.args | nindent 12 }}
The indentation does not look correct. Please check.

2024-05-20 11:33 UTC, AkshaySainiDell commented on charts/csi-powermax/templates/node.yaml
> +              value: "60"
I think this should be read from values.yaml files. Please check.

2024-06-12 13:01 UTC, boyamurthy reviewed
Please add api Port and podmon image in values.yaml file .

2024-06-17 07:27 UTC, boyamurthy approved these changes

2024-06-17 08:11 UTC, AkshaySainiDell approved these changes
LGTM

2024-06-17 08:13 UTC, chimanjain approved these changes

2024-06-17 09:31 UTC, merged