Karavi topology cert prom
dell/helm-charts pull request #93
Opened 2021-05-25 20:43 UTC by medegw01

#### Is this a new chart?

No

#### What this PR does / why we need it:
Prevents cert-manager from modifying passed certificates and ensures that self-singed certificates can be used for CA verification

#### Which issue(s) is this PR associated with:

- https://github.com/dell/karavi-observability/issues/52

#### Special notes for your reviewer:
The topology self-signed certificate is missing Key Usage and will get illegal characters if used for CA verification. Now the certificated looks:
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            2a:f9:d2:63:30:b9:17:4d:38:9e:21:e3:0e:fd:89:b4
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: O=dellemc
        Validity
            Not Before: May 25 20:26:43 2021 GMT
            Not After : Aug 23 20:26:43 2021 GMT
        Subject: O=dellemc
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:d9:b8:06:7d:a5:a2:a7:f9:d7:66:02:05:13:34:
                    be:ac:b6:65:35:9a:57:09:bd:86:89:34:c2:5a:b7:
                    63:04:de:63:2d:0a:f6:1e:32:af:1e:e0:45:ab:b0:
                    dd:e2:d1:e5:dc:5e:ca:13:3d:39:43:a6:e0:b4:64:
                    62:d5:6b:63:07:60:3d:19:4e:aa:5d:5c:23:7c:2e:
                    47:e9:d5:76:52:da:25:14:e6:91:4b:54:77:8a:a4:
                    7e:10:83:cd:25:7f:64:a4:45:d2:cc:3d:34:c0:cb:
                    af:0f:b2:a3:97:d8:d0:35:64:f4:66:93:c2:67:89:
                    27:eb:3f:00:fa:3c:a6:50:15:56:31:e1:ff:33:c4:
                    ef:9a:dc:64:45:1e:8a:6b:3b:a0:54:93:47:4e:03:
                    af:a4:8c:e4:38:80:8b:b6:0b:00:f9:a5:8e:19:9e:
                    b2:9c:c6:39:44:f4:30:cf:26:21:46:9b:ea:d6:fa:
                    d2:73:83:44:0f:c8:68:0f:ac:d0:b1:25:ea:b7:53:
                    18:f8:31:31:ac:9b:d4:83:02:d0:f7:c6:60:af:c3:
                    77:4c:19:c3:d4:0b:ff:d9:0a:8e:cf:07:7b:a2:58:
                    9b:15:f9:4f:55:ce:c1:77:47:2b:a1:c7:4c:29:02:
                    38:54:50:da:13:5f:a5:71:05:c6:92:43:26:f4:66:
                    1b:45
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Certificate Sign
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Key Identifier:
                62:C6:48:B7:D7:F7:B3:E4:C1:79:4C:EC:AD:87:F0:09:16:C9:DF:6D
            X509v3 Subject Alternative Name:
                DNS:karavi-topology, DNS:karavi-topology.karavi.svc.kubernetes.local
    Signature Algorithm: sha256WithRSAEncryption
         05:8f:2f:6c:35:e5:47:30:90:c0:28:aa:fd:52:5c:5f:02:4c:
         59:98:02:b6:71:94:60:ef:31:09:02:5c:5f:de:2d:d0:3a:c8:
         1b:2c:d8:3e:94:c9:ef:98:a5:f3:de:df:6a:4a:65:9d:f6:42:
         d5:0c:51:a2:63:71:1e:34:bb:bd:46:26:ab:5e:b8:92:62:ce:
         de:78:68:ca:5a:9a:6f:52:18:70:6b:52:3f:49:88:a6:1d:5a:
         19:57:6a:9a:14:d8:5a:b3:30:e3:1b:e6:93:03:df:b9:10:e4:
         48:43:d3:e3:5c:6c:a7:ac:01:fd:37:4e:05:f5:9b:16:c3:ce:
         85:3f:12:46:6d:75:a1:3a:bf:27:6e:ce:04:fe:03:70:c2:75:
         ca:78:da:53:12:e6:21:96:25:5d:12:30:63:62:05:5c:1c:1c:
         60:11:71:dc:1a:30:1c:06:d3:9c:6c:5a:a4:cd:c5:33:5d:e1:
         91:ce:79:75:ba:7a:4a:05:b0:21:2f:ef:16:9b:78:77:7c:13:
         46:cb:b0:c9:22:40:e8:64:47:b6:3c:38:0a:dc:c1:19:73:de:
         b0:45:8e:e3:de:fe:e6:fd:65:85:98:ab:45:7f:a5:f7:e8:e4:
         6c:b0:16:57:33:9b:f3:c0:03:96:ef:bc:df:69:ff:0e:00:f3:
         4a:12:75:42
```

#### Checklist:

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Chart Version bumped
- [ ] Variables are documented in the chart README.md
- [ ] Title of the PR starts with the chart name (e.g. `[charts_dir/mychartname]`) if applicable

2021-05-26 19:54 UTC, alikdell approved these changes

2021-06-02 06:59 UTC, coulof requested changes

2021-06-02 06:59 UTC, coulof commented on charts/karavi-observability/templates/cert-manager.yaml
>    - otel-collector.karavi.svc.kubernetes.local
Shouldn't we variable-ize the dns name with the namespace ?

If I install the module in `powerflex` NS the service URL will be `otel-collector.powerflex.svc.kubernetes.local`

2021-06-02 06:59 UTC, coulof commented on charts/karavi-observability/templates/cert-manager.yaml
>    - karavi-topology.karavi.svc.kubernetes.local
Same here, the FQDN should be `karavi-topology.{{ .Release.Namespace }}.svc.kubernetes.local`

2021-06-09 17:40 UTC, sharmilarama approved these changes

2021-07-07 18:30 UTC, medegw01 commented
Closing this PR as the content does not align with the intended plan for the cert manager. Cert-manager should be able to modify(generate a new certificate from the provided CA root certificate)  when the user-provided certificate expires

2021-07-07 18:30 UTC, closed without merging